authentication/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from authentication import views as l_views
from authentication.views import (
    login,
    register,
    logout,
    AuthenticationPasswordResetView,
)

app_name = "log"

urlpatterns = [
    path(
        "password_reset/",
        AuthenticationPasswordResetView.as_view(extra_context={"compa": "compa"}),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(extra_context={"compa": "compa"}),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            extra_context={"compa": "compa"},
            success_url=reverse_lazy("authentication:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(extra_context={"compa": "compa"}),
        name="password_reset_complete",
    ),
    path("login/", login, name="login"),
    path("register/", register, name="register"),
    path("logout/", logout, name="logout"),
]

core/urls.py
# Django
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Views
from authentication import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.welcome),
    path("", include("authentication.urls", namespace="authentication")),
    path("settings/", include("settings.urls", namespace="settings")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
import uuid

# Django
from django.conf import settings
from django.dispatch import receiver
from django.db.models.signals import post_save

# Models
from django.db import models
from django.contrib.auth.models import User


def user_directory_path(instance, filename):
    """ File will be uploaded to MEDIA_ROOT/<user_id>/<filename> """

    ext = filename.split(".")[-1]
    name = uuid.uuid4()
    return f"users/{instance.user.id}/{name}.{ext}"


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=50, null=True)
    phone = models.CharField(max_length=18, null=True)
    avatar = models.ImageField(
        upload_to=user_directory_path, default="avatar/default.png"
    )

    def __str__(self):
        return "Usuario: %s" % (self.user)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.userprofile.save()

authentication/forms.py
# Django
from django import forms

# Models
from authentication.models import UserProfile
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name")


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ("avatar", "address", "phone")

authentication/views.py
# Django
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from authentication.forms import UserProfileForm, UserForm
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import logout as do_logout
from django.contrib.auth import login as do_login
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate
from django.urls import reverse, reverse_lazy
from django.conf import settings

# Models
from django.contrib.auth.models import User
from settings.models import Setting

# CCBV
from django.contrib.auth.views import PasswordResetView


def welcome(request):
    # Si estamos identificados devolvemos la portada
    if request.user.is_authenticated:
        return render(request, "authentication/welcome.html")
    # En otro caso redireccionamos al login
    return redirect(settings.LOGIN_URL)


def login(request):
    # We check if the user is loggin
    if request.user.is_authenticated:
        return redirect(settings.LOGIN_REDIRECT_URL)
    # Creamos el formulario de autenticación vacío
    form = AuthenticationForm()
    if request.method == "POST":
        # Añadimos los datos recibidos al formulario
        form = AuthenticationForm(data=request.POST)
        # Si el formulario es válido...
        if form.is_valid():
            # Recuperamos las credenciales validadas
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            # Verificamos las credenciales del usuario
            user = authenticate(username=username, password=password)

            # Si existe un usuario con ese nombre y contraseña
            if user is not None:
                # Hacemos el login manualmente
                do_login(request, user)
                # Y le redireccionamos a la portada
                return redirect(settings.LOGIN_REDIRECT_URL)

    # Si llegamos al final renderizamos el formulario
    return render(request, "authentication/login.html", {"form": form})


def register(request):
    template = "authentication/register.html"
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            if user is not None:
                do_login(request, user)
                return redirect(settings.LOGIN_REDIRECT_URL)

    context = {"form": form}

    return render(request, template, context)


def logout(request):
    # Finalizamos la sesión
    do_logout(request)
    # Redireccionamos a la portada
    return redirect(settings.LOGOUT_REDIRECT_URL)


class AuthenticationPasswordResetView(PasswordResetView):

    html_email_template_name = "registration/password_reset_email_html.html"
    success_url = reverse_lazy("authentication:password_reset_done")

    def __init__(self, **kwargs):
        """
        Constructor. Called in the URLconf; can contain helpful extra
        keyword arguments, and other things.
        """
        # Go through keyword arguments, and either save their values to our
        # instance, or raise an error.

        for key, value in kwargs.items():
            setattr(self, key, value)

        setattr(self, "extra_email_context", self.set_extra_email_context())

    def set_extra_email_context(self):
        settings = Setting.objects.get(pk=1)
        context = {
            "SITE_NAME": settings.name,
            "SITE_PHONE_NUMBER": settings.phone_number,
            "SOCIAL_NETWORKS": {
                "INSTAGRAM": settings.instagram,
                "FACEBOOK": settings.facebook,
                "TWITTER": settings.twitter,
            },
        }
        return context

authentication/templates/authentication/base.html
{% load static %}
<!DOCTYPE html>
<html class="loading" lang="es-CL" data-textdirection="ltr">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta name="author" content="The Coders Company">
        <title>{% block title %}{% endblock %}</title>
        <link rel="apple-touch-icon" href="{% static 'app-assets/images/favicon/apple-touch-icon-152x152.png' %}">
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'app-assets/images/favicon/favicon-32x32.png' %}">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/vendors.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/themes/vertical-modern-menu-template/materialize.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/themes/vertical-modern-menu-template/style.css' %}">
        {% block css %}{% endblock %}
        <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/custom/custom.css' %}">
    </head>
    
    {% block body %}{% endblock %}
    
    <script src="{% static 'app-assets/js/vendors.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'app-assets/js/plugins.js' %}" type="text/javascript"></script>
    <script src="{% static 'app-assets/js/custom/custom-script.js' %}" type="text/javascript"></script>
    <script src="{% static 'app-assets/js/scripts/ui-alerts.js' %}" type="text/javascript"></script>
</html>

authentication/templates/authentication/forgot-password.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block title %}
Restablecer contraseña
{% endblock%}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/pages/forgot.css' %}">
{% endblock %}

{% block body %}
<body class="vertical-layout vertical-menu-collapsible page-header-dark vertical-modern-menu 1-column forgot-bg  blank-page blank-page" data-open="click" data-menu="vertical-modern-menu" data-col="1-column">
    <div class="row">
        <div class="col s12">
            <div class="container">
                <div id="forgot-password" class="row">
                    <div class="col s12 m6 l4 z-depth-4 offset-m4 card-panel border-radius-6 forgot-card bg-opacity-8">
                        <form class="login-form">
                            <div class="row">
                                <div class="input-field col s12">
                                    <h5 class="ml-4">Se te olvidó tu contraseña</h5>
                                    <p class="ml-4">Puedes restablecer tu contraseña ingresando tu email</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12">
                                    <i class="material-icons prefix pt-2">person_outline</i>
                                    <input id="email" type="email">
                                    <label for="email" class="center-align">Email</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12">
                                    <button type="submit" class="btn waves-effect waves-light border-round gradient-45deg-purple-deep-orange col s12 mb-1">
                                        Recuperar contraseña
                                    </button>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6 m6 l6">
                                    <p class="margin medium-small">
                                        <a href="/login">Iniciar sesión</a>
                                    </p>
                                </div>
                                <div class="input-field col s6 m6 l6">
                                    <p class="margin right-align medium-small">
                                        <a href="/register">Registrarse</a>
                                    </p>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}

authentication/templates/authentication/login.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block title %}
Iniciar sesión
{% endblock%}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/pages/login.css' %}">
{% endblock %}

{% block body %}
    <body class="vertical-layout vertical-menu-collapsible page-header-dark vertical-modern-menu 1-column login-bg  blank-page blank-page" data-open="click" data-menu="vertical-modern-menu" data-col="1-column">
        <div class="row">
            <div class="col s12">
                <div class="container">
                    <div id="login-page" class="row">
                        <div class="col s12 m6 l4 z-depth-4 card-panel border-radius-6 login-card bg-opacity-8">
                            {% if form.errors %}
                            <div class="card-alert card red">
                                <div class="card-content white-text">
                                    {{form.non_field_errors}}
                                </div>
                                <button type="button" class="close white-text" data-dismiss="alert" aria-label="Cerrar">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                            {% endif %}
                            <form class="login-form" method="POST">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="input-field col s12">
                                        <h5 class="ml-4">Iniciar sesión</h5>
                                    </div>
                                </div>
                                <div class="row margin">
                                    <div class="input-field col s12">
                                        <i class="material-icons prefix pt-2">person_outline</i>
                                        <input name="username" id="id_username" type="text" autofocus required>
                                        <label for="id_username" class="center-align">Usuario</label>
                                    </div>
                                </div>
                                <div class="row margin">
                                    <div class="input-field col s12">
                                        <i class="material-icons prefix pt-2">lock_outline</i>
                                        <input name="password" id="id_password" type="password" autofocus required>
                                        <label for="id_password">Contraseña</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col s12 m12 l12 ml-2 mt-1">
                                        <p>
                                            <label>
                                                <input type="checkbox" />
                                                <span>Recordar</span>
                                            </label>
                                        </p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s12">
                                        <button type="submit" class="btn waves-effect waves-light border-round gradient-45deg-purple-deep-orange col s12">Entrar</button>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s6 m6 l6">
                                        <p class="margin medium-small"><a href="{% url 'authentication:register' %}">¡Regístrate ahora!</a></p>
                                    </div>
                                    <div class="input-field col s6 m6 l6">
                                        <p class="margin right-align medium-small"><a href="{% url 'authentication:password_reset' %}">Recuperar contraseña</a></p>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
{% endblock %}

authentication/templates/authentication/register.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block title %}
Registrarse
{% endblock%}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/pages/register.css' %}">
{% endblock %}

{% block body %}
<body class="vertical-layout vertical-menu-collapsible page-header-dark vertical-modern-menu 1-column register-bg  blank-page blank-page" data-open="click" data-menu="vertical-modern-menu" data-col="1-column">
    <div class="row">
        <div class="col s12">
            <div class="container">
                <div id="register-page" class="row">
                    <div class="col s12 m6 l4 z-depth-4 card-panel border-radius-6 register-card bg-opacity-8">
                        <form class="login-form" method="POST">
                            {% csrf_token %}
                            <div class="row">
                                <div class="input-field col s12">
                                    <h5 class="ml-4">Registro</h5>
                                    <p class="ml-4">¡Únete a nuestra comunidad ahora!</p>
                                </div>
                            </div>

                            {% include 'generic/forms/input.html' with field=form.username label="Nombre usuario" col="s12" %}
                            {% include 'generic/forms/input.html' with field=form.password1 label="Contraseña" col="s12" %}
                            {% include 'generic/forms/input.html' with field=form.password2 label="Contraseña (Confirmación)" col="s12" %}

                            <div class="row">
                                <div class="input-field col s12">
                                    <button class="btn waves-effect waves-light border-round gradient-45deg-purple-deep-orange col s12" type="submit">Registrarte</button>   
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12">
                                    <p class="margin medium-small"><a href="/login">¿Ya tienes una cuenta? Inicia sesión</a></p>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}

authentication/templates/authentication/welcome.html
{% extends 'generic/base.html' %}
{% block title %}
Dashboard {{hola}}
{% endblock %}