core/urls.py
# Django
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Views
from authentication import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.welcome),
    path("", include("authentication.urls", namespace="authentication")),
    path("settings/", include("settings.urls", namespace="settings")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

settings/urls.py
from django.urls import path
from settings.views import index, template_options

app_name = "settings"

urlpatterns = [
    path("", index, name="index"),
    path("template", template_options, name="customizer"),
]

settings/models.py
import uuid

# Django
from django.db import models


def setting_directory_path(instance, filename):
    """ File will be uploaded to MEDIA_ROOT/site/logo/<filename> """

    ext = filename.split(".")[-1]
    name = uuid.uuid4()
    return f"site/logo/{name}.{ext}"


class Setting(models.Model):
    name = models.CharField(max_length=128)
    slogan = models.CharField(max_length=128)
    logo = models.ImageField(upload_to=setting_directory_path, null=True)
    email = models.EmailField(max_length=128)
    phone_number = models.CharField(max_length=15)
    intro_step = models.PositiveSmallIntegerField(default=1)
    description = models.CharField(max_length=240)
    keywords = models.CharField(max_length=240)

    # Social networks
    instagram = models.CharField(max_length=128, blank=True)
    twitter = models.CharField(max_length=128, blank=True)
    facebook = models.CharField(max_length=128, blank=True)

    # Template settings

    ## Menu options
    menu_color = models.PositiveSmallIntegerField()
    menu_dark = models.BooleanField()
    menu_collapsed = models.BooleanField()
    menu_selection = models.PositiveSmallIntegerField()

    ## Navbar options
    navbar_color = models.PositiveSmallIntegerField()
    navbar_dark = models.BooleanField()
    navbar_fixed = models.BooleanField()

    ## Footer options
    footer_dark = models.BooleanField()
    footer_fixed = models.BooleanField()

    def __str__(self):
        return self.name

settings/forms.py
# Django
from django import forms

# Models
from settings.models import Setting


class SettingForm(forms.ModelForm):
    class Meta:
        model = Setting
        exclude = ("intro_step",)

settings/views.py
# Django
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from django.contrib import messages

# Models
from settings.models import Setting

# Forms
from settings.forms import SettingForm


@login_required
def index(request):

    setting = get_object_or_404(Setting, pk=1)

    if request.method == "POST":
        form = SettingForm(data=request.POST, files=request.FILES, instance=setting)
        form.save()
        messages.success(request, "Sitio actualizado!")
    else:
        form = SettingForm(instance=setting)

    context = {"menu": "settings", "form": form}

    return render(request, "settings/index.html", context)


@login_required
def template_options(request):

    setting = Setting.objects.get(pk=1)

    param = list(request.GET.keys())[0]
    value = request.GET.get(param)
    value = int(value) if value.isdigit else value
    value = bool(value) if type(getattr(setting, param)) == bool else value

    setattr(setting, param, value)

    setting.save()

    return JsonResponse({param: getattr(setting, param)})

settings/templates/settings/index.html
{% extends 'generic/form.html' %}

{% block title %}Configuración{% endblock %}

{% block form_page_title %}
  <i class="material-icons">settings</i>
  Configuración
{% endblock %}

{% block form_page_subtitle_description %}Configure su sitio{% endblock %}

{% block form_title %}
  <i class="material-icons">settings</i>
  Complete el formulario para configurar su sitio
{% endblock %}

{% block form_sidebar_title %}Necesitas configurar tu sitio?{% endblock %}

{% block form_sidebar_description %}Estás en el lugar correcto! sigue las indicaciones para configurar tu sitio.{% endblock %}

{% block content_form %}
  {{form.errors}}
  {% include 'generic/forms/input.html' with field=form.logo name="logo" default=form.instance.logo.url %}
  {% include 'generic/forms/input.html' with field=form.name label="Nombre" col="s12" %}
  {% include 'generic/forms/input.html' with field=form.slogan label="Slogan" col="s12" %}
  {% include 'generic/forms/input.html' with field=form.email label="Email de soporte" col="s12" %}
  {% include 'generic/forms/input.html' with field=form.phone_number label="Teléfono de contacto" col="s12" %}
  {% include 'generic/forms/input.html' with field=form.description label="Descripción" col="s12" %}
  {% include 'generic/forms/input.html' with field=form.keywords label="Palabras clave" col="s12" %}

  {% include 'generic/forms/input.html' with field=form.instagram label="Instagram" col="s12" %}
  {% include 'generic/forms/input.html' with field=form.facebook label="Facebook" col="s12" %}
  {% include 'generic/forms/input.html' with field=form.twitter label="Twitter" col="s12" %}
{% endblock %}

{% block customizer %}
  {% include 'customizer/customizer.html' %}
{% endblock %}

{% block pageleveljs %}
    <script>
        $('#id_logo').dropify({
            messages: {
                default: 'Agrega un logo al sitio',
                replace: 'Haz clic para reemplazar la imagen',
                remove:  'Quitar',
                error:   'El tipo de documento no valido'
            }
        });
    </script>
{% endblock %}