authentication/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from authentication import views as l_views
from authentication.views import (
    login,
    register,
    logout,
    AuthenticationPasswordResetView,
)

app_name = "log"

urlpatterns = [
    path(
        "password_reset/",
        AuthenticationPasswordResetView.as_view(extra_context={"compa": "compa"}),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(extra_context={"compa": "compa"}),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            extra_context={"compa": "compa"},
            success_url=reverse_lazy("authentication:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(extra_context={"compa": "compa"}),
        name="password_reset_complete",
    ),
    path("login/", login, name="login"),
    path("register/", register, name="register"),
    path("logout/", logout, name="logout"),
]

core/urls.py
# Django
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Views
from authentication import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.welcome),
    path("", include("authentication.urls", namespace="authentication")),
    path("settings/", include("settings.urls", namespace="settings")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

settings/urls.py
from django.urls import path
from settings.views import index, template_options

app_name = "settings"

urlpatterns = [
    path("", index, name="index"),
    path("template", template_options, name="customizer"),
]

users/urls.py
from django.urls import path
from users.views import *

app_name = "users"

urlpatterns = [
    path("", index, name="index"),
    path("list", get_users_list, name="datatable"),
    path("create", create, name="create"),
    path("<int:id>/delete", delete, name="delete"),
    path("<int:id>/edit", update, name="edit"),
]

templates/generic/base.html
{% load static %}
<!DOCTYPE html>
<html class="loading" lang="es-CL" data-textdirection="ltr">
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
      <meta name="description" content="{{SITE_DESCRIPTION}}">
      <meta name="keywords" content="{{SITE_KEYWORDS}}">
      <meta name="author" content="The Coders Company">
      <title>{% block title %}{% endblock %} - {{SITE_NAME}}</title>
      <link rel="apple-touch-icon" href="{% static 'app-assets/images/favicon/apple-touch-icon-152x152.png' %}">
      <link rel="shortcut icon" type="image/x-icon" href="{% static 'app-assets/images/favicon/favicon-32x32.png' %}">
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/vendors.min.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/flag-icon/css/flag-icon.min.css' %}">
      {% block vendorcss %}{% endblock %}
      <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/themes/vertical-modern-menu-template/materialize.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/themes/vertical-modern-menu-template/style.css' %}">
      {% block pagelevelcss %}{% endblock %}
      <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/custom/custom.css' %}">
      {% block customcss %}{% endblock %}
   </head>
   <body class="vertical-layout vertical-menu-collapsible page-header-dark vertical-modern-menu 2-columns app-page" data-open="click" data-menu="vertical-modern-menu" data-col="2-columns">
      <!-- BEGIN: Header-->
      {% include 'generic/header.html' %}
      <!-- END: Header-->

      <!-- BEGIN: SideNav-->
      {% include 'generic/sidenav.html' %}
      <!-- END: SideNav-->

      <!-- BEGIN: Page Main-->
      <div id="main" {% if MENU_COLLAPSED %}class="main-full"{% endif %}>
         <div class="row">
            <div class="content-wrapper-before {{NAVBAR_COLOR}}"></div>
            <div class="col s12">
               <div class="container">
                  {% block container %}{% endblock %}
               </div>
            </div>
         </div>
      </div>
      <!-- END: Page Main-->

      {% block modal %}{% endblock %}

      <!-- Theme Customizer -->
      {% block customizer %}{% endblock %}
      <!--/ Theme Customizer -->

      <footer class="page-footer footer {{FOOTER_DARK_CLASS}} gradient-shadow navbar-border navbar-shadow {% if FOOTER_FIXED %}footer-fixed{% else %}footer-static{% endif %}">
         <div class="footer-copyright">
            <div class="container"><span>&copy; 2020 <a href="/" target="_blank">{{SITE_NAME}}</a> Todos los derechos reservados.</span><span class="right hide-on-small-only">Desarrollado por <a href="#">The Coders Company</a></span></div>
         </div>   
      </footer>

      <script src="{% static 'app-assets/js/vendors.min.js' %}" type="text/javascript"></script>
      <script src="{% static 'app-assets/vendors/sweetalert/sweetalert.min.js' %}"></script>
      <script>
         function themeCustomizer(event) {
            let qname = event.getAttribute('name')
            let qvalue = null
            
            if (event.type === "checkbox") {
               qvalue = event.checked === true ? 1 : 0
            } else {
               qvalue = event.dataset.code || event.value
            }
            
            fetch("{% url 'settings:customizer' %}?" + qname + "=" + qvalue)
            .then(data => data.json())
            .then(res => {
               console.log('hi', res)
            })
            
         }
      </script>

      {% block vendorjs %}{% endblock %}
      {% block pagevendorjs %}{% endblock%}
      {% block themejs %}{% endblock%}
      {% block pageleveljs %}{% endblock%}

      {% if messages %}
      <script>
         {% for message in messages %}
         {% if message.level == 25 %}
         swal("Listo!", "{{message}} ", "success")
         {% elif message.level == 40 %}
         swal("Algo paso!", "{{message}} ", "error")
         {% endif %}
         {% endfor %}
      </script>
      {% endif %}
   </body>
</html>

templates/generic/form.html
{% extends 'generic/base.html' %}
{% load static %}

{% block vendorcss %}
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/fonts/fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/dropify/css/dropify.min.css' %}">
{% endblock %}

{% block pagelevelcss %}
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/pages/page-contact.css' %}">
{% endblock %}

{% block customcss %}
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/custom/custom.css' %}">
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
{% endblock %}

{% block container %}
    <div id="contact-us" class="section">
        <div class="app-wrapper">
            <div class="contact-header">
                <div class="row contact-us">
                    <div class="col s12 m12 l4 sidebar-title">
                        <h5 class="m-0">
                            {% block form_page_title %}{% endblock %}
                        </h5>
                        <p class="m-0 font-weight-500 mt-6 hide-on-med-and-down text-ellipsis">
                            {% block form_page_subtitle_description %}{% endblock %}
                        </p>
                    </div>
                    <div class="col s12 m12 l8 form-header">
                        <h6 class="form-header-text">
                            {% block form_title %}{% endblock %}
                        </h6>
                    </div>
                </div>
            </div>

            <!-- Contact Sidenav -->
            <div id="sidebar-list" class="row contact-sidenav">
                <div class="col s12 m12 l4">
                    <!-- Sidebar Area Starts -->
                    <div class="sidebar-left sidebar-fixed">
                        <div class="sidebar">
                            <div class="sidebar-content">
                                <div class="sidebar-menu list-group position-relative">
                                    <div class="sidebar-list-padding app-sidebar contact-app-sidebar" id="contact-sidenav">
                                        <ul class="contact-list display-grid">
                                            <li>
                                            <h5 class="m-0">{% block form_sidebar_title %}{% endblock %}</h5>
                                            </li>
                                            <li>
                                            <h6 class="mt-5 line-height">{% block form_sidebar_description %}{% endblock %}</h6>
                                            </li>
                                            <li>
                                            <hr class="mt-5">
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            
                                <a href="#" data-target="contact-sidenav" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                            
                            </div>
                        </div>
                    </div>
                    <!-- Sidebar Area Ends -->
                </div>
                <div class="col s12 m12 l8 contact-form margin-top-contact">
                    <div class="row">
                        <form class="col s12" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% block content_form %}{% endblock %}
                            <div class="input-field col s12 width-100">
                                <button type="submit" class="waves-effect waves-light btn">Enviar</button>
                            </div>                
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock%}

{% block vendorjs %}
    <script src="{% static 'app-assets/vendors/dropify/js/dropify.min.js' %}"></script>
{% endblock %}

{% block themejs %}
    <script src="{% static 'app-assets/js/plugins.js' %}" type="text/javascript"></script>
    <script src="{% static 'app-assets/js/custom/custom-script.js' %}" type="text/javascript"></script>
    <script src="{% static 'app-assets/js/scripts/customizer.js' %}" type="text/javascript"></script>
{% endblock%}

{% block pageleveljs %}
    <script src="{% static 'app-assets/js/scripts/page-contact.js' %}" type="text/javascript"></script>
    <script src="{% static 'app-assets/js/scripts/ui-alerts.js' %}" type="text/javascript"></script>
{% endblock%}

templates/generic/header.html
{% load static %}

<header class="page-topbar" id="header">
    <div class="navbar{% if NAVBAR_FIXED %} navbar-fixed{% endif %}"> 
        <nav class="navbar-main navbar-color nav-collapsible sideNav-lock navbar-dark {{NAVBAR_COLOR}} no-shadow">
            <div class="nav-wrapper">
                <div class="header-search-wrapper hide-on-med-and-down"><i class="material-icons">search</i>
                    <input class="header-search-input z-depth-2" type="text" name="Search" placeholder="Explorar" disabled>
                </div>
                <ul class="navbar-list right">
                    <li class="hide-on-med-and-down"><a class="waves-effect waves-block waves-light translation-button" href="javascript:void(0);" data-target="translation-dropdown"><span class="flag-icon flag-icon-gb"></span></a></li>
                    <li class="hide-on-med-and-down"><a class="waves-effect waves-block waves-light toggle-fullscreen" href="javascript:void(0);"><i class="material-icons">settings_overscan</i></a></li>
                    <li class="hide-on-large-only"><a class="waves-effect waves-block waves-light search-button" href="javascript:void(0);"><i class="material-icons">search</i></a></li>
                    <li><a class="waves-effect waves-block waves-light notification-button" href="javascript:void(0);" data-target="notifications-dropdown"><i class="material-icons">notifications_none<small class="notification-badge">1</small></i></a></li>
                    <li><a class="waves-effect waves-block waves-light profile-button" href="javascript:void(0);" data-target="profile-dropdown"><span class="avatar-status avatar-online"><img src="{% get_media_prefix %}{{request.user.userprofile.avatar}}" alt="avatar"><i></i></span></a></li>
                    <li><a class="waves-effect waves-block waves-light sidenav-trigger" href="#" data-target="slide-out-right"><i class="material-icons">format_indent_increase</i></a></li>
                </ul>
                <!-- translation-button-->
                <ul class="dropdown-content" id="translation-dropdown">
                    <li><a class="grey-text text-darken-1" href="#!"><i class="flag-icon flag-icon-gb"></i> English</a></li>
                    <li><a class="grey-text text-darken-1" href="#!"><i class="flag-icon flag-icon-es"></i> Spanish</a></li>
                    <li><a class="grey-text text-darken-1" href="#!"><i class="flag-icon flag-icon-fr"></i> French</a></li>
                    <li><a class="grey-text text-darken-1" href="#!"><i class="flag-icon flag-icon-cn"></i> Chinese</a></li>
                    <li><a class="grey-text text-darken-1" href="#!"><i class="flag-icon flag-icon-de"></i> German</a></li>
                </ul>
                <!-- notifications-dropdown-->
                <ul class="dropdown-content" id="notifications-dropdown">
                    <li>
                        <h6>Notificaciones<span class="new badge">1</span></h6>
                    </li>
                    <li class="divider"></li>
                    
                    <li><a class="grey-text text-darken-2" href="#!"><span class="material-icons icon-bg-circle teal small">settings</span> Settings updated</a>
                        <time class="media-meta" datetime="2015-06-12T20:50:48+08:00">4 days ago</time>
                    </li>
                </ul>
                <!-- profile-dropdown-->
                <ul class="dropdown-content" id="profile-dropdown">
                    <li><a class="grey-text text-darken-1" href="{% url 'users:edit' request.user.id %}"><i class="material-icons">person_outline</i> Perfil</a></li>
                    <li class="divider"></li>
                    <li><a class="grey-text text-darken-1" href="#"><i class="material-icons">lock_outline</i> Bloquear</a></li>
                    <li><a class="grey-text text-darken-1" href="{% url 'authentication:logout' %}"><i class="material-icons">keyboard_tab</i> Cerrar sesión</a></li>
                </ul>
            </div>
            <nav class="display-none search-sm">
            <div class="nav-wrapper">
                <form>
                <div class="input-field">
                    <input class="search-box-sm" type="search" required="">
                    <label class="label-icon" for="search"><i class="material-icons search-sm-icon">search</i></label><i class="material-icons search-sm-close">close</i>
                </div>
                </form>
            </div>
            </nav>
        </nav>
    </div>
</header>

templates/generic/sidenav.html
{% load static %}
<aside class="sidenav-main nav-expanded nav-collapsible sidenav-light {{MENU_SELECTION_CLASS}} {% if MENU_COLLAPSED %}nav-collapsed{% else %}nav-lock{% endif %}">
    <div class="brand-sidebar">
        <h1 class="logo-wrapper">
            <a class="brand-logo darken-1" href="/">
                <img src="{% static 'app-assets/images/logo/logo-color.png' %}" alt="logo"/>
                <span class="logo-text hide-on-med-and-down">Dashboard</span>
            </a>
            <a class="navbar-toggler" href="#"><i class="material-icons">radio_button_checked</i></a>
        </h1>
    </div>
    <ul class="sidenav sidenav-collapsible leftside-navigation collapsible sidenav-fixed menu-shadow" id="slide-out" data-menu="menu-navigation" data-collapsible="menu-accordion">
        <li class="bold"><a class="collapsible-header waves-effect waves-cyan " href="#"><i class="material-icons">settings_input_svideo</i><span class="menu-title" data-i18n="">Dashboard</span></a>
            <div class="collapsible-body">
                <ul class="collapsible collapsible-sub" data-collapsible="accordion">
                    <li><a class="collapsible-body" href="#" data-i18n=""><i class="material-icons">radio_button_unchecked</i><span>Work in progress</span></a></li>
                </ul>
            </div>
        </li>
        {% if request.user.is_superuser %}
            <li class="{% if menu == 'users' %}active{% endif %} bold"><a class="waves-effect waves-cyan {% if menu == 'users' %}active {{MENU_COLOR}}{% endif %}" href="{% url 'users:index' %}"><i class="material-icons">group</i><span class="menu-title" data-i18n="">Usuarios</span></a> </li>
            <li class="{% if menu == 'settings' %}active{% endif %} bold"><a class="waves-effect waves-cyan {% if menu == 'settings' %}active {{MENU_COLOR}}{% endif %}" href="{% url 'settings:index' %}"><i class="material-icons">settings</i><span class="menu-title" data-i18n="">Configuración</span></a> </li>
        {% endif %}
        <li class="navigation-header"><a class="navigation-header-text">Ayuda </a><i class="navigation-header-icon material-icons">more_horiz</i></li>
        <li class="bold"><a class="waves-effect waves-cyan " href="#"><i class="material-icons">import_contacts</i><span class="menu-title" data-i18n="">Preguntas frecuentes</span></a></li>
        <li class="bold"><a class="waves-effect waves-cyan " href="#"><i class="material-icons">help_outline</i><span class="menu-title" data-i18n="">Soporte</span></a></li>
    </ul>
    <div class="navigation-background"></div><a class="sidenav-trigger btn-sidenav-toggle btn-floating btn-medium waves-effect waves-light hide-on-large-only" href="#" data-target="slide-out"><i class="material-icons">menu</i></a>
</aside>