core/urls.py
# Django
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Views
from authentication import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.welcome),
    path("", include("authentication.urls", namespace="authentication")),
    path("settings/", include("settings.urls", namespace="settings")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import *

app_name = "users"

urlpatterns = [
    path("", index, name="index"),
    path("list", get_users_list, name="datatable"),
    path("create", create, name="create"),
    path("<int:id>/delete", delete, name="delete"),
    path("<int:id>/edit", update, name="edit"),
]

authentication/models.py
import uuid

# Django
from django.conf import settings
from django.dispatch import receiver
from django.db.models.signals import post_save

# Models
from django.db import models
from django.contrib.auth.models import User


def user_directory_path(instance, filename):
    """ File will be uploaded to MEDIA_ROOT/<user_id>/<filename> """

    ext = filename.split(".")[-1]
    name = uuid.uuid4()
    return f"users/{instance.user.id}/{name}.{ext}"


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=50, null=True)
    phone = models.CharField(max_length=18, null=True)
    avatar = models.ImageField(
        upload_to=user_directory_path, default="avatar/default.png"
    )

    def __str__(self):
        return "Usuario: %s" % (self.user)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.userprofile.save()

users/models.py
from django.db import models

# Create your models here.

users/views.py
import json

# Django
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.contrib import messages
from django.urls import reverse

## Django: Views
from django.views.generic import CreateView

# Models
from authentication.models import UserProfile
from django.contrib.auth.models import User

# Forms
from authentication.forms import UserForm, UserProfileForm

# Utils
from core.utils import DataTable
from .decorators import admin_only


@login_required
@admin_only
def get_users_list(request):
    """ API for load data in DataTable """

    active_users = request.GET.get("active")
    dt = DataTable(request)

    if active_users == "true":
        users_list = UserProfile.objects.filter(user__is_active=True)
    elif active_users == "false":
        users_list = UserProfile.objects.filter(user__is_active=False)
    else:
        users_list = UserProfile.objects.filter(
            user__first_name__contains=dt.search
        ) | UserProfile.objects.filter(user__last_name__contains=dt.search)

    # Pagination
    paginator = Paginator(list(users_list), 15)
    users = paginator.get_page(dt.start)
    # Prepare data
    def sort_data(profile):
        return [
            profile.user.first_name + " " + profile.user.last_name,
            profile.user.email,
            '<a href="/users/'
            + str(profile.user.pk)
            + '/edit"><i class="material-icons">edit</i></a>\
            <a href="#" ><i onclick="remove(event);return false;" data-user-id="'
            + str(profile.user.pk)
            + '" class="material-icons">delete</i></a>',
        ]

    data_users = list(map(sort_data, users.object_list))

    data = {
        "draw": dt.draw,
        "recordsTotal": paginator.count,
        "recordsFiltered": paginator.count,
        "data": data_users,
    }

    return JsonResponse(data, safe=False)


@login_required
@admin_only
def index(request):

    total_users = UserProfile.objects.all().count()

    context = {
        "total_users": total_users,
        "menu": "users",
    }
    return render(request, "users/index.html", context)


@login_required
@admin_only
def create(request):

    if request.method == "POST":
        user_form = UserForm(request.POST)

        if user_form.is_valid():
            user = user_form.save()
            UserProfile.objects.create(user=user)
            messages.success(request, "Usuario creado!")
            return redirect(reverse("users:index"))

    else:
        user_form = UserForm()

    context = {
        "user_form": user_form,
        "menu": "users",
    }

    return render(request, "users/create.html", context)


@login_required
def update(request, id):
    """ Update User data """

    user = get_object_or_404(User, pk=id)

    if not (request.user == user or request.user.is_superuser):
        raise PermissionDenied

    user_form = UserForm(data=request.POST or None, instance=user)

    profile_form = UserProfileForm(
        data=request.POST or None,
        files=request.FILES or None,
        instance=user.userprofile,
    )

    if user_form.is_valid() and profile_form.is_valid():
        user_form.save()
        profile_form.save()
        messages.success(request, "Usuario actualizado!")

    context = {"user_form": user_form, "profile_form": profile_form, "menu": "users"}
    return render(request, "users/update.html", context)


@login_required
@admin_only
def delete(request, id):
    user = get_object_or_404(User, pk=id)
    user.delete()
    data = {"ok": True}
    return JsonResponse(data)

users/templates/users/create.html
{% extends 'generic/form.html' %}

{% block title %}Nuevo usuario{% endblock %}

{% block form_page_title %}
    <i class="material-icons contact-icon vertical-text-top">person_add</i>
    Nuevo usuario
{% endblock %}

{% block form_page_subtitle_description %}Agregue un nuevo usuario{% endblock %}

{% block form_title %}
    <i class="material-icons">person_add</i>
    Complete el formulario para agregar un nuevo usuario
{% endblock %}

{% block form_sidebar_title %}Necesitas agregar un nuevo usuario?{% endblock %}

{% block form_sidebar_description %}Estás en el lugar correcto! sigue las indicaciones para crear el usuario.{% endblock %}

{% block content_form %}
    {{user_form.as_p}}
{% endblock %}

users/templates/users/index.html
{% extends 'generic/base.html' %}
{% load static %}

{% block title %}
Usuarios
{% endblock %}

{% block vendorcss %}
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/data-tables/css/jquery.dataTables.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/data-tables/extensions/responsive/css/responsive.dataTables.min.css' %}">
{% endblock %}

{% block pagelevelcss %}
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/pages/app-sidebar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/pages/app-contacts.css' %}">
{% endblock %}

{% block customcss %}{% endblock %}

{% block container %}
<!-- Add new contact popup -->
<div style="bottom: 54px; right: 19px;" class="fixed-action-btn direction-top">
    <a class="btn-floating btn-large primary-text gradient-shadow modal-trigger" href="{% url 'users:create' %}">
        <i class="material-icons">person_add</i>
    </a>
</div>
<!-- Add new contact popup Ends-->
      
<!-- Sidebar Area Starts -->
<div class="sidebar-left sidebar-fixed">
    <div class="sidebar">
        <div class="sidebar-content">
            <div class="sidebar-header">
                <div class="sidebar-details">
                    <h5 class="m-0 sidebar-title"><i class="material-icons app-header-icon text-top">group</i> Usuarios</h5>
                    <div class="mt-10 pt-2">
                        <p class="m-0 subtitle font-weight-700">Total de usuarios</p>
                        <p class="m-0 text-muted">{{total_users}} Usuarios</p>
                        
                    </div>
                </div>
            </div>
            <div id="sidebar-list" class="sidebar-menu list-group position-relative animate fadeLeft delay-1">
                <div class="sidebar-list-padding app-sidebar sidenav" id="contact-sidenav">
                    <ul id="sub-menu" class="contact-list display-grid">
                        <li class="sidebar-title">Filtros</li>
                        <li class="active">
                            <a href="{% url 'users:index' %}" class="text-sub">
                                <i class="material-icons mr-2"> perm_identity </i> Todos los usuarios
                            </a>
                        </li>
                        <li class="sidebar-title">Estado</li>
                        <li>
                            <a href="#" data-active="true" class="text-sub status-filter">
                                <i class="green-text material-icons small-icons mr-2">fiber_manual_record</i> Activo
                            </a>
                        </li>
                        <li>
                            <a href="#" data-active="false" class="text-sub status-filter">
                                <i class="red-text material-icons small-icons mr-2">fiber_manual_record</i> Inactivo
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <a href="#" data-target="contact-sidenav" class="sidenav-trigger hide-on-large-only">
                <i class="material-icons">menu</i>
            </a>
        </div>
    </div>
</div>
<!-- Sidebar Area Ends -->
      
<!-- Content Area Starts -->
<div class="content-area content-right">
    <div class="app-wrapper">
        <div class="datatable-search">
            <i class="material-icons mr-2 search-icon">search</i>
            <input type="text" placeholder="Buscar usuario" class="app-filter" id="global_filter">
        </div>
        <div id="button-trigger" class="card card card-default scrollspy border-radius-6 fixed-width">
            <div class="card-content p-0">
                <table id="data-table" class="display" style="width:100%">
                <thead>
                    <tr>
                        <th>Nombres</th>
                        <th>Email</th>
                        <th>Acción</th>
                    </tr>
                </thead>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- Content Area Ends -->
{% endblock %}

{% block pagevendorjs %}
    <script src="{% static 'app-assets/vendors/data-tables/js/jquery.dataTables.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'app-assets/vendors/data-tables/extensions/responsive/js/dataTables.responsive.min.js' %}" type="text/javascript"></script>
{% endblock%}

{% block themejs %}
    <script src="{% static 'app-assets/js/plugins.js' %}" type="text/javascript"></script>
    <script src="{% static 'app-assets/js/custom/custom-script.js' %}" type="text/javascript"></script>
    <script src="{% static 'app-assets/js/scripts/customizer.js' %}" type="text/javascript"></script>
{% endblock%}

{% block pageleveljs %}
    <script src="{% static 'app-assets/js/scripts/app-users.js' %}" type="text/javascript"></script>
    <script>
    function remove(event) {
        event.stopPropagation()
        userId = event.target.dataset.userId
        swal({
            title: "Estas seguro?",
            text: "Se eliminará el usuario seleccionado",
            icon: 'warning',
            buttons: {
                cancel: 'Cancelar',
                delete: 'Aceptar'
            }
        })
        .then(id => {
            fetch('/users/' + userId + '/delete')
            .then(data => data.json())
            .then(json => {
                $('#data-table').DataTable().ajax.reload()
                swal({ title: 'Listo!', icon: 'success' })
            })
        })
    }
    </script>
{% endblock%}

users/templates/users/update.html
{% extends 'generic/form.html' %}

{% block title %}Actualizar usuario{% endblock %}

{% block form_page_title %}
    <i class="material-icons">edit</i>
    Actualizar usuario
{% endblock %}

{% block form_page_subtitle_description %}Actualice al usuario seleccionado{% endblock %}

{% block form_title %}
    <i class="material-icons">edit</i>
    Complete el formulario para actualizar al usuario
{% endblock %}

{% block form_sidebar_title %}Necesitas actualizar a un usuario?{% endblock %}

{% block form_sidebar_description %}Estás en el lugar correcto! sigue las indicaciones para actualizar al usuario.{% endblock %}

{% block content_form %}
    <div class="row">
        {% include 'generic/forms/input.html' with field=profile_form.avatar default=profile_form.instance.avatar.url %}
        {% include 'generic/forms/input.html' with field=user_form.first_name label="Nombre" col="s12 m6" %}
        {% include 'generic/forms/input.html' with field=user_form.last_name label="Apellido" col="s12 m6" %}
        {% include 'generic/forms/input.html' with field=user_form.username label="Usuario" col="s12 m6" %}
        {% include 'generic/forms/input.html' with field=user_form.email label="Email" col="s12 m6" %}
        {% include 'generic/forms/input.html' with field=profile_form.address label="Dirección" col="s12 m6" %}
        {% include 'generic/forms/input.html' with field=profile_form.phone label="Teléfono" col="s12 m6" %}
    </div>
{% endblock %}

{% block pageleveljs %}
    <script>
        $('#id_avatar').dropify({
            messages: {
                default: 'Agrega una imagen de perfil',
                replace: 'Haz clic para reemplazar la imagen',
                remove:  'Quitar',
                error:   'El tipo de documento no valido'
            }
        });
    </script>
{% endblock %}